### ISSUE TITLE
Document units of the data

### ISSUE THREAD

**Issue by davkovacs** [BingqingCheng/ab-initio-thermodynamics-of-water#1]
Could you please add documentation of the units of the dataset. The standard units for GAP are eV and A, but I believe this dataset uses eV and Bohr which would be important to point out.

**Comment by BingqingCheng** [comment]
Yes, the units here is in eV and Bohr. I'll add a note.

You can find the xyz in eV/A here:
https://github.com/BingqingCheng/Mapping-the-space-of-materials-and-molecules/tree/master/mlp-water

**Comment by davkovacs** [comment]
Thank you!
